/** Prints the exact saved document using the shared image renderer; no unreviewed local snapshot. */
export const MANUAL_PRINT_CSS = `.manual-print-preview{position:fixed;inset:0;z-index:50;background:#f2f6f7;overflow:auto;color:#183039}.manual-print-toolbar{position:sticky;top:0;display:flex;align-items:center;gap:12px;background:white;border-bottom:1px solid #d7e2e5;padding:12px 24px;z-index:2}.manual-print-toolbar p{margin:0;flex:1}.manual-print-document{max-width:920px;margin:28px auto;background:white;padding:48px;box-sizing:border-box}.manual-print-document>header{border-top:6px solid var(--print-accent,#087f7a);padding:28px 0}.manual-print-document h1{font-size:32px;line-height:1.4;margin:12px 0}.manual-print-document>header>img{max-width:180px;max-height:72px;object-fit:contain;object-position:left}.manual-print-step{break-inside:avoid;border-top:1px solid #d7e2e5;padding:24px 0}.manual-print-step>img{display:block;width:100%;max-height:560px;object-fit:contain}.manual-print-step p{white-space:pre-wrap;line-height:1.7}@media(max-width:760px){.manual-print-document{margin:12px;padding:24px}.manual-print-toolbar{padding:8px 12px;flex-wrap:wrap}.manual-print-toolbar p{flex-basis:100%;font-size:13px}.manual-print-document h1{font-size:24px}}@media print{body>*:not(.manual-print-preview){display:none!important}.manual-print-preview{position:static;overflow:visible;background:white}.manual-print-toolbar{display:none}.manual-print-document{margin:0;padding:0;max-width:none}.manual-print-document>header{print-color-adjust:exact}.manual-print-step{page-break-inside:avoid}.manual-print-step>img{max-height:660px}}`;
export const MANUAL_PRINT_JS = `
  const printBlobDataUrl=blob=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error("画像を読み込めませんでした。"));reader.readAsDataURL(blob);});
  async function openPrintPreview(trigger) {
    if(dirty||saveInFlight||activeCloudImageEditor||cloudImageBusy||pendingImageJobs.size){setMessage("変更を保存してから、PDF・印刷を開いてください。","warning");return;}
    const snapshot=clone(detailData);if(!snapshot?.draft)return;
    const preview=make("section","","manual-print-preview");preview.setAttribute("aria-label","PDF・印刷プレビュー");const toolbar=make("div","","manual-print-toolbar"),status=make("p","保存済みの手順書を読み込んでいます…"),close=make("button","編集に戻る","secondary"),print=make("button","PDF / 印刷","primary");close.type=print.type="button";print.disabled=true;status.setAttribute("role","status");toolbar.append(status,close,print);preview.append(toolbar);document.body.append(preview);let closed=false;const urls=[];
    const dismiss=()=>{closed=true;urls.forEach(url=>URL.revokeObjectURL(url));preview.remove();trigger?.focus();};close.addEventListener("click",dismiss);preview.addEventListener("keydown",event=>{if(event.key==="Escape")dismiss();});print.addEventListener("click",()=>{if(!print.disabled)window.print();});close.focus();
    const paper=make("article","","manual-print-document"),heading=make("header");paper.style.setProperty("--print-accent",/^#[0-9a-f]{6}$/i.test(snapshot.branding?.themeColor||"")?snapshot.branding.themeColor:"#087f7a");heading.append(make("h1",snapshot.draft.title),make("p",snapshot.draft.description||""),make("p",snapshot.steps.length+" 手順 · 保存済みの内容"));paper.append(heading);preview.append(paper);
    try {
      const logoUrl=safeBrandLogoUrl(snapshot.branding?.logoUrl);if(logoUrl){const logo=make("img");logo.alt="チームのロゴ";logo.src=logoUrl;await logo.decode();heading.prepend(logo);}
      for(const [index,step] of snapshot.steps.entries()){if(closed)return;const section=make("section","","manual-print-step");section.append(make("h2","手順 "+(index+1)+"："+(step.title||"手順")));paper.append(section);if(step.assetId){const path=imageUrlFor(step);if(!path)throw new Error("画像の参照を確認できません。");const response=await fetch(path,{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error("手順 "+(index+1)+" の画像を読み込めませんでした。");const url=await printBlobDataUrl(await response.blob());const image=new Image();image.src=url;await image.decode();const canvas=document.createElement("canvas");canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;imageTools().drawScreenshot(canvas.getContext("2d"),image,{annotations:step.annotations||[],masks:[]});const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/png"));if(!blob)throw new Error("画像を描画できません。");const output=await printBlobDataUrl(blob);const rendered=make("img");rendered.src=output;rendered.alt="手順 "+(index+1)+" の画像";await rendered.decode();section.append(rendered);}section.append(make("p",step.instruction||""));}
      if(!closed){status.textContent="保存済みの内容です。印刷画面で「PDFに保存」を選べます。";print.disabled=false;}
    }catch(error){if(!closed){status.textContent=(error.message||"プレビューを作成できませんでした。")+" 編集に戻って、もう一度お試しください。";status.className="cloud-image-error";}}
  }
`;
