/** Workspace branding settings; the server remains authoritative for roles, CAS and raster checks. */
export const MANUAL_BRANDING_CSS = `.branding-dialog{width:min(560px,calc(100vw - 40px));max-height:90dvh;box-sizing:border-box;padding:28px;border:1px solid #789099;border-radius:16px;color:#183039;background:#fff;font:15px/1.65 system-ui}.branding-dialog::backdrop{background:#18303966}.branding-dialog h2{margin:0 0 8px;font-size:23px}.branding-dialog>button:first-child{float:right}.branding-dialog label{display:grid;gap:6px;margin:18px 0;font-weight:650}.branding-dialog input{font:inherit;min-height:44px;border:1px solid #789099;border-radius:8px;padding:8px;box-sizing:border-box;max-width:100%}.branding-dialog input[type=color]{width:88px}.branding-dialog .branding-colors{display:flex;align-items:center;gap:12px}.branding-preview{padding:24px;border:1px solid #d7e2e5;border-top:6px solid var(--preview-accent,#087f7a);border-radius:10px;background:#fff}.branding-preview img,.manual-team-logo{object-fit:contain;max-width:160px;max-height:52px;padding:6px;box-sizing:border-box;background:#fff}.branding-preview strong{display:block;font-size:19px}.branding-preview .branding-tag{display:inline-block;margin-top:12px;border-radius:6px;padding:6px 12px;background:var(--preview-accent,#087f7a);color:var(--preview-foreground,#fff)}.branding-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:24px}.branding-feedback{min-height:24px;white-space:pre-line}.branding-feedback[data-error=true]{color:#a3362b}.manual-output-brand{display:flex;align-items:center;gap:12px;border-left:4px solid var(--manual-accent);padding:4px 12px;margin-bottom:18px;color:var(--manual-muted);font-size:12px}.manual-toolbar .manual-team-logo{max-width:112px;max-height:40px}@media(max-width:760px){.branding-dialog{padding:20px}.manual-toolbar .manual-team-logo{display:none}.branding-actions{flex-wrap:wrap}.branding-dialog h2{font-size:21px}}`;
export const MANUAL_BRANDING_JS = `
  function brandingForeground(hex) { const v=hex.slice(1).match(/../g).map(value=>parseInt(value,16)/255).map(c=>c<=.04045?c/12.92:Math.pow((c+.055)/1.055,2.4));const light=v[0]*.2126+v[1]*.7152+v[2]*.0722;return (light+.05)/.05>=1.05/(light+.05)?"#000000":"#ffffff"; }
  function applyManualBranding(data) { const branding=data?.branding;const color=/^#[0-9a-f]{6}$/i.test(branding?.themeColor||"")?branding.themeColor:"#087f7a";root.style.setProperty("--manual-accent",color);root.style.setProperty("--manual-foreground",brandingForeground(color)); }
  function safeBrandLogoUrl(value) { if(typeof value!=="string")return null;try{const u=new URL(value,location.origin);return u.origin===location.origin&&u.pathname.startsWith(workspacePath()+"/branding/logos/")&&!u.search&&!u.hash?u.href:null;}catch{return null;} }
  async function openBrandingSettings(trigger) {
    if(document.querySelector(".branding-dialog"))return;
    const dialog=make("dialog","","branding-dialog");dialog.setAttribute("aria-label","チームの見た目");
    const close=make("button","閉じる","secondary");close.type="button";close.addEventListener("click",()=>dialog.close());dialog.append(close,make("h2","チームの見た目"),make("p","チームカラーとロゴを設定します。新しい手順書の標準になります。手順書ごとに設定した見た目と、作成済みの共有リンクは変わりません。","cloud-note"));
    const feedback=make("p","設定を読み込んでいます…","branding-feedback");feedback.setAttribute("role","status");dialog.append(feedback);document.body.append(dialog);dialog.addEventListener("close",()=>{dialog.remove();trigger?.focus();});dialog.showModal();
    try {
      const result=await json(workspacePath()+"/branding");if(!dialog.isConnected)return;let saved=result.branding||{};const canEdit=result.permissions?.canEdit===true;let pendingLogo=null,logoJob=null,removeLogo=false,busy=false;
      feedback.textContent=canEdit?"ロゴはPNG・JPEG・WebPで追加できます。SVGや外部URLは使用しません。":"設定を変更できるのはオーナー・管理者です。";
      const colorLabel=make("label","チームカラー");const colors=make("div","","branding-colors"),picker=document.createElement("input"),hex=document.createElement("input");picker.type="color";picker.value=saved.themeColor||"#087f7a";picker.setAttribute("aria-label","チームカラーを選択");hex.value=picker.value;hex.setAttribute("aria-label","チームカラーのカラーコード");hex.maxLength=7;hex.pattern="#[0-9A-Fa-f]{6}";picker.disabled=hex.disabled=!canEdit;colors.append(picker,hex);colorLabel.append(colors);
      const logoLabel=make("label","チームのロゴ");const file=document.createElement("input");file.type="file";file.accept="image/png,image/jpeg,image/webp";file.disabled=!canEdit;file.setAttribute("aria-label","チームのロゴ");logoLabel.append(file);
      const preview=make("section","","branding-preview");preview.setAttribute("aria-label","手順書の見た目のプレビュー");const logo=document.createElement("img");logo.alt="チームのロゴ";logo.hidden=true;const initialLogo=safeBrandLogoUrl(saved.logoUrl);if(initialLogo){logo.src=initialLogo;logo.hidden=false;}logo.addEventListener("error",()=>{logo.hidden=true;feedback.textContent="ロゴを読み込めませんでした。保存済みの設定は変更していません。";});const badge=make("span","手順 1","branding-tag");preview.append(logo,make("strong",editorState?.title||"はじめての手順書"),make("p","大事な操作が、ひと目で伝わる手順書に。"),badge);
      const remove=make("button","ロゴを外す","secondary");remove.type="button";remove.disabled=!canEdit;remove.addEventListener("click",()=>{if(busy)return;pendingLogo=null;logoJob=null;removeLogo=true;logo.hidden=true;logo.removeAttribute("src");file.value="";});
      const updatePreview=()=>{if(/^#[0-9a-f]{6}$/i.test(hex.value)){picker.value=hex.value;preview.style.setProperty("--preview-accent",hex.value);preview.style.setProperty("--preview-foreground",brandingForeground(hex.value));}};picker.addEventListener("input",()=>{hex.value=picker.value;updatePreview();});hex.addEventListener("input",updatePreview);updatePreview();
      file.addEventListener("change",async()=>{const value=file.files?.[0];if(!value||busy)return;busy=true;save.disabled=true;feedback.textContent="ロゴを安全な画像に変換しています…";try{const normalized=await imageTools().normalizeUploadedImage(value);const image=new Image();image.src=normalized.dataUrl;await image.decode();const ratio=Math.min(1,1024/image.naturalWidth,512/image.naturalHeight);const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(image.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(image.naturalHeight*ratio));canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,"image/png"));if(!blob||blob.size>1024*1024)throw new Error("ロゴは変換後1MB以内にしてください。");pendingLogo=blob;logoJob=null;removeLogo=false;logo.src=canvas.toDataURL("image/png");logo.hidden=false;feedback.textContent="ロゴを確認して、設定を保存してください。";feedback.dataset.error="false";}catch(error){file.value="";feedback.textContent=error.message||"ロゴを読み込めませんでした。";feedback.dataset.error="true";}finally{busy=false;save.disabled=!canEdit;}});
      const actions=make("div","","branding-actions"),cancel=make("button","キャンセル","secondary"),save=make("button","設定を保存","primary");cancel.type=save.type="button";save.disabled=!canEdit;cancel.addEventListener("click",()=>dialog.close());actions.append(cancel,save);dialog.append(colorLabel,logoLabel,remove,preview,actions);
      save.addEventListener("click",async()=>{if(busy||!canEdit)return;if(!/^#[0-9a-f]{6}$/i.test(hex.value)){feedback.textContent="カラーコードを #087f7a の形式で入力してください。";feedback.dataset.error="true";hex.focus();return;}busy=true;save.disabled=true;close.disabled=cancel.disabled=true;feedback.textContent="設定を保存しています…";try{let logoId=removeLogo?null:saved.logoId||null;if(pendingLogo){if(!logoJob){const bytes=await pendingLogo.arrayBuffer();logoJob={id:randomBase64Url(),bytes,checksum:Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes)),v=>v.toString(16).padStart(2,"0")).join("")};}const uploaded=await json(workspacePath()+"/branding/logos/"+logoJob.id,{method:"PUT",headers:{"Content-Type":"image/png","x-asset-sha256":logoJob.checksum,"x-asset-byte-length":String(logoJob.bytes.byteLength)},body:logoJob.bytes});logoId=uploaded.logoId;}const desired={themeColor:hex.value.toLowerCase(),logoId,expectedVersionId:saved.versionId||null};let response;try{response=await json(workspacePath()+"/branding",{method:"PATCH",body:JSON.stringify(desired)});}catch(error){const current=await json(workspacePath()+"/branding");if(current.branding?.themeColor!==desired.themeColor||(current.branding?.logoId||null)!==desired.logoId)throw error;response=current;}saved=response.branding;pendingLogo=null;logoJob=null;feedback.textContent="設定を保存しました。新しく作る手順書の標準として使われます。";feedback.dataset.error="false";if(editorState)markChanged();}catch(error){feedback.textContent=error.message||"設定を保存できませんでした。入力内容は保持しています。";feedback.dataset.error="true";}finally{busy=false;save.disabled=!canEdit;close.disabled=cancel.disabled=false;}});
      dialog.addEventListener("cancel",event=>{if(busy)event.preventDefault();});
    }catch(error){feedback.textContent=error.message||"設定を読み込めませんでした。閉じてもう一度お試しください。";feedback.dataset.error="true";}
  }
`;
