import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { createHash } from 'node:crypto';
import { mkdir, readFile } from 'node:fs/promises';
import test from 'node:test';
import { chromium } from './support/test-browser.mjs';
import { CLOUD_MANUAL_CSS, CLOUD_MANUAL_JS, renderCloudManualsPage } from '../apps/worker/src/cloud-manual-assets.ts';
import { EDITOR_TOOLS_JS } from '../apps/worker/src/editor-tools-assets.ts';

test('shared cloud image tools preserve rectangles, safe uploads, branding and printable output at three widths', {timeout:180_000}, async()=>{
  let png,version=1,branding={versionId:null,themeColor:'#087f7a',foregroundColor:'#ffffff',logoId:null,logoUrl:null};
  const uploads=[],patches=[];const assets=new Map();
  let steps=Array.from({length:20},(_,i)=>({id:'step-'+(i+1),position:i+1,type:'action',title:['顧客一覧を開く','詳細を確認する','変更を確認する','保存する'][i%4],instruction:'内容を確認して、保存をクリックします。',assetId:'initial',assetUrl:'/api/workspaces/team/assets/initial',annotations:[{id:'rect-'+i,type:'rectangle',x:.72,y:.72,width:.2,height:.13,color:'#df4a36',strokeWidth:4}]}));
  const server=createServer(async(req,res)=>{try{
    const path=new URL(req.url,'http://localhost').pathname;res.setHeader('content-security-policy',"default-src 'self'; base-uri 'none'; connect-src 'self'; font-src 'self'; form-action 'self'; frame-ancestors 'none'; img-src 'self' data:; script-src 'self'; style-src 'self'");const send=(body,type='application/json',status=200)=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store'});res.end(type==='application/json'?JSON.stringify(body):body);};
    if(path==='/seed')return send('<!doctype html><html lang="ja"><body></body></html>','text/html');
    if(path==='/manuals')return send(renderCloudManualsPage({workspaceId:'team'}),'text/html');
    if(path==='/assets/cloud-manual.css')return send(CLOUD_MANUAL_CSS,'text/css');
    if(path==='/assets/cloud-manual.js')return send(CLOUD_MANUAL_JS,'application/javascript');
    if(path==='/assets/editor-tools.js')return send(EDITOR_TOOLS_JS,'application/javascript');
    const brandAsset=path==='/s/assets/brand/logo.png'?'meccha-manual-logo-mark.png':path==='/s/assets/brand/mascot.png'?'meccha-manual-mascot-me-clear-eyes.png':null;
    if(brandAsset)return send(await readFile(new URL('../apps/worker/brand-assets/assets/'+brandAsset,import.meta.url)),'image/png');
    if(path==='/api/workspaces/team/manuals')return send({manuals:[{id:'manual',title:'顧客情報を更新する'}]});
    if(path.endsWith('/share-links'))return send({share:null});
    if(path==='/api/workspaces/team/manuals/manual')return send({manual:{id:'manual',title:'顧客情報を更新する'},draft:{id:'draft',title:'顧客情報を更新する',description:'合成データで確認する20手順の手順書',updatedAt:'v'+version,contentVersion:'a'.repeat(32)},steps,branding,permissions:{canEdit:true}});
    if(path.startsWith('/api/workspaces/team/assets/'))return send(assets.get(path.split('/').at(-1))||png,'image/png');
    if(path==='/api/workspaces/team/branding'&&req.method==='GET')return send({branding,permissions:{canEdit:true}});
    if(path.startsWith('/api/workspaces/team/branding/logos/')&&req.method==='GET')return send(assets.get('logo')||png,'image/png');
    const chunks=[];for await(const chunk of req)chunks.push(chunk);const bytes=Buffer.concat(chunks);
    if(req.method==='PUT'){
      assert.equal(req.headers['content-type'],'image/png');assert.equal(Number(req.headers['x-asset-byte-length']),bytes.length);assert.equal(req.headers['x-asset-sha256'],createHash('sha256').update(bytes).digest('hex'));assert.deepEqual([...bytes.subarray(0,8)],[137,80,78,71,13,10,26,10]);uploads.push({path,bytes});
      if(path.includes('/branding/logos/')){assets.set('logo',bytes);return send({status:'ready',logoId:'logo',logoUrl:'/api/workspaces/team/branding/logos/logo'});}
      const id='uploaded-'+uploads.length;assets.set(id,bytes);return send({status:'ready',assetId:id,assetUrl:'/api/workspaces/team/assets/'+id,revisionId:'draft',expectedUpdatedAt:'v'+version});
    }
    const body=bytes.length?JSON.parse(bytes):{};
    if(path==='/api/workspaces/team/branding'&&req.method==='PATCH'){assert.equal(body.expectedVersionId,branding.versionId);branding={...body,versionId:'brand-'+version,foregroundColor:'#ffffff',logoUrl:body.logoId?'/api/workspaces/team/branding/logos/logo':null};return send({branding});}
    if(path.endsWith('/draft')&&req.method==='PATCH'){patches.push(body);steps=body.steps.map((s,i)=>({...s,position:i+1,assetUrl:'/api/workspaces/team/assets/'+s.assetId}));version++;return send({status:'saved',updatedAt:'v'+version});}
    return send({message:'not found'},'application/json',404);
  }catch(error){res.writeHead(500).end(String(error));}});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;let browser;
  try{
    browser=await chromium.launch({channel:'chromium',headless:true});await mkdir('.artifacts/uiux-20261001/screens',{recursive:true});
    const seed=await browser.newPage();await seed.goto(origin+'/seed');png=Buffer.from(await seed.evaluate(()=>{const c=document.createElement('canvas');c.width=1200;c.height=660;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.fillStyle='#eaf2f4';x.fillRect(0,0,1200,64);x.fillStyle='#193039';x.font='26px system-ui';x.fillText('サンプル顧客管理',32,42);x.font='bold 32px system-ui';x.fillText('顧客情報を確認',40,126);x.fillStyle='#f6fafb';x.fillRect(180,180,970,68);x.strokeStyle='#cbdadc';x.strokeRect(180,180,970,68);x.fillStyle='#526671';x.font='26px system-ui';x.fillText('氏名',40,224);x.fillStyle='#193039';x.fillText('見本 花子',200,224);x.fillStyle='#087f7a';x.fillRect(900,484,224,72);x.fillStyle='#fff';x.fillText('保存する',942,532);return c.toDataURL('image/png').split(',')[1];}),'base64');await seed.close();
    for(const [width,height] of [[1366,900],[1024,768],[390,844]]){
      const page=await browser.newPage({viewport:{width,height},locale:'ja-JP'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{window.__cspViolations=[];addEventListener('securitypolicyviolation',event=>window.__cspViolations.push(event.violatedDirective+':'+event.blockedURI));});
      await page.goto(origin+'/manuals');await page.getByRole('button',{name:'顧客情報を更新する',exact:true}).waitFor();await page.screenshot({path:'.artifacts/uiux-20261001/screens/list-'+width+'.png',fullPage:true});await page.getByRole('button',{name:'顧客情報を更新する',exact:true}).click();
      if(width<=760)await page.locator('.manual-mobile-actions').getByRole('button',{name:'手順',exact:true}).click();await page.locator('.manual-step-nav [data-step-key="step-17"]').click();
      const openTools=async()=>{if(width<=1100)await page.getByRole('button',{name:width<=760?'編集':'画像・編集',exact:true}).click();};
      await openTools();await page.getByRole('button',{name:'矢印・文字を追加',exact:true}).click();await page.locator('#imageEditorDialog').waitFor();await page.locator('[data-editor-save]').waitFor();await page.waitForFunction(()=>document.querySelector('#imageEditorDialog canvas')?.width===1200&&!document.querySelector('[data-editor-save]')?.disabled);
      const rectangle=page.locator('[data-editor-selection] button').filter({hasText:/四角/}).first();await rectangle.click();const color=page.locator('[data-editor-color]');await color.fill('#a14eba');await color.dispatchEvent('input');assert.equal(await page.locator('[data-color-label]').textContent(),'枠線の色');assert.equal(await page.getByRole('textbox',{name:'色のカラーコード',exact:true}).inputValue(),'#a14eba');assert.equal(await page.locator('[data-manual-save]').isDisabled(),true);assert.ok((await color.boundingBox()).height>=44);if(width>760){const footer=await page.locator('.image-editor-actions').boundingBox();assert.ok(footer.y+footer.height<=height+1,'Image Apply/Cancel footer stays inside the visible editor');assert.ok(await page.locator('.image-editor-canvas-wrap').evaluate(el=>el.scrollWidth<=el.clientWidth+1),'Fit image must not create sideways scrolling');}
      if(width===390){const header=await page.locator('.image-editor-form>header').boundingBox(),canvas=await page.locator('#imageEditorCanvas').boundingBox(),tools=await page.locator('.image-editor-tools').boundingBox(),footer=await page.locator('.image-editor-actions').boundingBox();assert.ok(canvas.y>=header.y+header.height-1,'image canvas is never hidden under its context header');assert.ok(canvas.y+canvas.height<=tools.y+1,'canvas and properties have independent nonoverlapping regions');assert.ok(canvas.x>=0&&canvas.x+canvas.width<=width+1,'full image width remains in the viewport');assert.ok(footer.y+footer.height<=height+1,'Apply and Cancel remain visible');}
      await page.screenshot({path:'.artifacts/uiux-20261001/screens/cloud-image-tools-'+width+'.png',fullPage:true});
      if(width===390){const hex=page.getByRole('textbox',{name:'色のカラーコード',exact:true});await hex.fill('#bad');await hex.dispatchEvent('input');assert.equal(await hex.getAttribute('aria-invalid'),'true');await page.locator('[data-editor-selection]').getByRole('button',{name:/を削除$/}).first().click();await page.locator('#imageEditorCanvas').focus();await page.keyboard.press('Control+z');assert.equal(await page.locator('[data-editor-color-hex]').getAttribute('aria-invalid'),null);assert.equal(await page.locator('[data-editor-selection] button').filter({hasText:/四角/}).count(),1);}
      await page.locator('[data-editor-save]').click();await page.locator('#imageEditorDialog').waitFor({state:'detached'});await page.getByRole('button',{name:'変更を保存',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.cloud-save-state')?.textContent==='クラウドに保存済み');assert.equal(steps.find(s=>s.id==='step-17').annotations[0].color,'#a14eba');
      await openTools();await page.getByRole('button',{name:'矢印・文字を追加',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-editor-save]')?.disabled);await page.locator('[data-editor-selection] button').filter({hasText:/四角/}).first().click();assert.equal(await page.locator('[data-editor-color]').inputValue(),'#a14eba');await page.locator('[data-editor-cancel]').first().click();
      await openTools();await page.getByRole('button',{name:'チームの見た目',exact:true}).click();await page.getByLabel('チームカラーのカラーコード').fill('#563aa3');await page.getByLabel('チームカラーのカラーコード').dispatchEvent('input');await page.getByLabel('チームのロゴ',{exact:true}).setInputFiles({name:'synthetic-logo.png',mimeType:'image/png',buffer:png});await page.getByRole('button',{name:'設定を保存',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.branding-actions .primary')?.disabled);await page.screenshot({path:'.artifacts/uiux-20261001/screens/settings-'+width+'.png',fullPage:true});await page.getByRole('button',{name:'設定を保存',exact:true}).click();await page.locator('.branding-feedback').filter({hasText:'設定を保存しました'}).waitFor();await page.locator('.branding-dialog').getByRole('button',{name:'閉じる',exact:true}).click();
      await page.getByRole('button',{name:'変更を保存',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.cloud-save-state')?.textContent==='クラウドに保存済み');
      await openTools();await page.getByRole('button',{name:'PDF・印刷プレビュー',exact:true}).click();await page.getByRole('button',{name:'PDF / 印刷',exact:true}).waitFor();await page.waitForFunction(()=>!document.querySelector('.manual-print-toolbar .primary')?.disabled);assert.equal(await page.locator('.manual-print-step').count(),20);assert.equal(await page.locator('.manual-print-document>header>img').count(),1);await page.screenshot({path:'.artifacts/uiux-20261001/screens/print-'+width+'.png'});await page.getByRole('button',{name:'編集に戻る',exact:true}).click();assert.equal(await page.locator('.cloud-step').getAttribute('data-step-key'),'step-17');
      if(width===390){
        await openTools();await page.getByRole('button',{name:'矢印・文字を追加',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('[data-editor-save]')?.disabled);await page.locator('[data-editor-tool="text"]').click();const canvas=page.locator('#imageEditorCanvas');const rect=await canvas.boundingBox();await canvas.click({position:{x:rect.width*.3,y:rect.height*.35}});await page.locator('[data-editor-text]').fill('SYNTHETIC_REDACTED_CLOUD_CANARY');await page.locator('.advanced-tools summary').click();await page.locator('[data-editor-tool="mask"]').click();await page.mouse.move(rect.x+rect.width*.2,rect.y+rect.height*.25);await page.mouse.down();await page.mouse.move(rect.x+rect.width*.8,rect.y+rect.height*.65,{steps:4});await page.mouse.up();await page.locator('[data-editor-save]').click();await page.locator('#imageEditorDialog').waitFor({state:'detached'});await page.getByRole('button',{name:'変更を保存',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.cloud-save-state')?.textContent==='クラウドに保存済み');assert.ok(!JSON.stringify(patches.at(-1)).includes('SYNTHETIC_REDACTED_CLOUD_CANARY'));assert.deepEqual(steps.find(step=>step.id==='step-17').annotations,[]);const bytes=uploads.at(-1).bytes;const pixel=await page.evaluate(async base64=>{const image=new Image();image.src='data:image/png;base64,'+base64;await image.decode();const c=document.createElement('canvas');c.width=image.naturalWidth;c.height=image.naturalHeight;const x=c.getContext('2d');x.drawImage(image,0,0);return [...x.getImageData(Math.round(c.width*.3),Math.round(c.height*.35),1,1).data];},bytes.toString('base64'));assert.deepEqual(pixel,[17,24,39,255]);
      }
      assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>window.__cspViolations),[]);await page.close();
    }
    assert.equal(patches.length,7);assert.ok(uploads.length>=6);
  }finally{await browser?.close();server.closeAllConnections?.();await new Promise(resolve=>server.close(resolve));}
});
