import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("sidepanel is the action surface and keeps recording controls explicit", async () => {
  const manifest = JSON.parse(await readFile(new URL("../apps/extension/manifest.json", import.meta.url), "utf8"));
  const html = await readFile(new URL("../apps/extension/sidepanel/sidepanel.html", import.meta.url), "utf8");
  const source = await readFile(new URL("../apps/extension/sidepanel/sidepanel.js", import.meta.url), "utf8");
  const css = await readFile(new URL("../apps/extension/sidepanel/sidepanel.css", import.meta.url), "utf8");
  assert.equal(manifest.version, "0.1.7");
  assert.equal(manifest.permissions.includes("sidePanel"), true);
  assert.equal(manifest.action.default_popup, undefined);
  assert.equal(manifest.action.default_icon["128"], "assets/meccha-manual-logo-mark.png");
  assert.equal(manifest.icons["128"], "assets/meccha-manual-logo-mark.png");
  assert.equal(manifest.side_panel.default_path, "sidepanel/sidepanel.html");
  assert.match(source, /capture:start/);
  assert.match(source, /capture:pause/);
  assert.match(source, /capture:finish/);
  assert.match(source, /capture:close-panel/);
  assert.match(source, /EDITOR_READY_TIMEOUT_MS/);
  assert.match(source, /waitForEditorReady/);
  assert.match(source, /isEditorReadySender/);
  assert.match(source, /openDraftEditor\(result\.draftId, \{ waitForReady: true \}\)/);
  assert.match(source, /keepLiveTailVisibleAfterResize\(\)/);
  assert.match(source, /liveLatest/);
  assert.match(source, /scrollLiveLatest/);
  assert.match(source, /window\.scrollTo\(\{ top: targetScrollY, behavior: scrollBehavior \}\)/);
  assert.match(source, /if \(programmaticFollowPending\) \{\s*if \(isLiveTailVisible\(\)\) programmaticFollowPending = false;/);
  assert.doesNotMatch(source, /event\?\.isTrusted\) programmaticFollowPending = false/);
  assert.doesNotMatch(source, /latest\.scrollIntoView/);
  assert.doesNotMatch(source, /window\.scrollBy\(\{ top: overlap/);
  assert.match(source, /captureLimitReached/);
  assert.match(source, /captureLimitReached: state\.captureLimitReached/);
  assert.match(source, /cancel_failed/);
  assert.match(source, /100/);
  assert.match(source, /200/);
  const worker = await readFile(new URL("../apps/extension/background/service-worker.js", import.meta.url), "utf8");
  assert.match(worker, /chrome\.sidePanel\.open/);
  assert.match(worker, /chrome\.sidePanel\.close/);
  assert.match(worker, /CLOUD_CLAIM_MAX_ASSETS/);
  assert.match(worker, /message\?\.type === "editor:ready"/);
  assert.doesNotMatch(worker, /typeof importedCaptureLiveStore/);
  assert.match(worker, /captureLimitReached: session\?\.captureLimitReached/);
  assert.match(source, /captureLiveStore\.list/);
  assert.match(html, /id="liveSteps"/);
  assert.match(html, /id="liveCurrentStep"/);
  assert.match(html, /id="liveCurrentStatus"/);
  assert.match(html, /id="liveLatest"/);
  assert.ok(html.indexOf('id="liveProgress"') < html.indexOf('id="liveSection"'), "live progress must precede the scrollable recording section");
  assert.match(html, /id="draftSection"/);
  assert.match(html, /id="finish"/);
  assert.match(html, /id="pause"/);
  assert.match(css, /prefers-reduced-motion/);
  assert.match(css, /\.live-progress \{[^}]*position: sticky/);
});
